config/routes.rb
Rails.application.routes.draw do

  root :to => "user#default_page"

  resources :user do
    get 'sign_up', :on => :collection
    post 'register_user', :on => :collection
    post 'login', :on => :collection
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def default_page
  end

  def sign_up
  end

  def register_user
    password = Digest::MD5.hexdigest(params[:user][:password])
    params[:user].merge!(:password=>password)
    user_params = params.require(:user).permit(:email_id,:password)
    User.create(user_params)
    redirect_to root_path, notice: "You have been signned up."
  end

  def login
    email = params[:user][:email_id]
    pwd = params[:user][:password]
    password = Digest::MD5.hexdigest(pwd)
    @user = User.where("email_id = ? and password = ?",email,password).first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PdfTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user/default_page.html.erb
<!DOCTYPE html>
<html>

<head>

  <meta charset="UTF-8">

  <title>Random Login Form - CodePen</title>

  <style>
      @import url(http://fonts.googleapis.com/css?family=Exo:100,200,400);
      @import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro:700,400,300);

      body{
          margin: 0;
          padding: 0;
          background: #fff;

          color: #fff;
          font-family: Arial;
          font-size: 12px;
      }

      .body{
          position: absolute;
          top: -20px;
          left: -20px;
          right: -40px;
          bottom: -40px;
          width: auto;
          height: auto;
          background-image: url(http://ginva.com/wp-content/uploads/2012/07/city-skyline-wallpapers-008.jpg);
          background-size: cover;
          -webkit-filter: blur(5px);
          z-index: 0;
      }

      .grad{
          position: absolute;
          top: -20px;
          left: -20px;
          right: -40px;
          bottom: -40px;
          width: auto;
          height: auto;
          background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(100%,rgba(0,0,0,0.65))); /* Chrome,Safari4+ */
          z-index: 1;
          opacity: 0.7;
      }

      .header{
          position: absolute;
          top: calc(50% - 35px);
          left: calc(50% - 255px);
          z-index: 2;
      }

      .header div{
          float: left;
          color: #fff;
          font-family: 'Exo', sans-serif;
          font-size: 35px;
          font-weight: 200;
      }

      .header div span{
          color: #5379fa !important;
      }

      .login{
          position: absolute;
          top: calc(50% - 75px);
          left: calc(50% - 50px);
          height: 150px;
          width: 350px;
          padding: 10px;
          z-index: 2;
      }

      .login input[type=text]{
          width: 250px;
          height: 30px;
          background: transparent;
          border: 1px solid rgba(255,255,255,0.6);
          border-radius: 2px;
          color: #fff;
          font-family: 'Exo', sans-serif;
          font-size: 16px;
          font-weight: 400;
          padding: 4px;
      }

      .login input[type=password]{
          width: 250px;
          height: 30px;
          background: transparent;
          border: 1px solid rgba(255,255,255,0.6);
          border-radius: 2px;
          color: #fff;
          font-family: 'Exo', sans-serif;
          font-size: 16px;
          font-weight: 400;
          padding: 4px;
          margin-top: 10px;
      }

      .login input[type=button]{
          width: 260px;
          height: 35px;
          background: #fff;
          border: 1px solid #fff;
          cursor: pointer;
          border-radius: 2px;
          color: #a18d6c;
          font-family: 'Exo', sans-serif;
          font-size: 16px;
          font-weight: 400;
          padding: 6px;
          margin-top: 10px;
      }

      .login input[type=button]:hover{
          opacity: 0.8;
      }

      .login input[type=button]:active{
          opacity: 0.6;
      }

      .login input[type=text]:focus{
          outline: none;
          border: 1px solid rgba(255,255,255,0.9);
      }

      .login input[type=password]:focus{
          outline: none;
          border: 1px solid rgba(255,255,255,0.9);
      }

      .login input[type=button]:focus{
          outline: none;
      }

      ::-webkit-input-placeholder{
          color: rgba(255,255,255,0.6);
      }

      ::-moz-input-placeholder{
          color: rgba(255,255,255,0.6);
      }
  </style>

  <script src="js/prefixfree.min.js"></script>

</head>

<body>

<div class="body"></div>
<div class="grad"></div>
<div class="header">
  <div>Site<span>Random</span></div>
</div>
<br>
<div class="login">
  <%= form_tag(login_user_index_path, multipart: true) %>
  <input type="text" placeholder="username" name="user[email_id]"><br>
  <input type="password" placeholder="password" name="user[password]"><br>
  <!--<input type="button" value="Login">-->
  <%= submit_tag "Sign in" %>
  <%= link_to "Sign Up", sign_up_user_index_path %>
</div>

<script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>

</body>

</html>

app/views/user/sign_up.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>


  <!-- General meta information -->
  <title>Login Form by Oussama Afellad</title>
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="robots" content="index, follow" />
  <meta charset="utf-8" />
  <!-- // General meta information -->


  <!-- Load Javascript -->
  <!--<script type="text/javascript" src="./js/jquery.js"></script>-->
  <!--<script type="text/javascript" src="./js/jquery.query-2.1.7.js"></script>-->
  <!--<script type="text/javascript" src="./js/rainbows.js"></script>-->
  <!-- // Load Javascipt -->

  <script>


      $(document).ready(function(){

          $("#submit1").hover(
                  function() {
                      $(this).animate({"opacity": "0"}, "slow");
                  },
                  function() {
                      $(this).animate({"opacity": "1"}, "slow");
                  });
      });


  </script>

</head>
<body>

<div id="wrapper">
  <div id="wrappertop"></div>

  <div id="wrappermiddle">
    <h2>Login</h2>
    <%= form_tag(register_user_user_index_path, multipart: true) %>
    <div id="username_input">
      <div id="username_inputleft"></div>
      <div id="username_inputmiddle">
        <input type="text" name="user[email_id]" id="url" value="E-mail Address" onclick="this.value = ''">
        <img id="url_user" src="/images/mailicon.png" alt="">
      </div>
      <div id="username_inputright"></div>
    </div>

    <div id="password_input">
      <div id="password_inputleft"></div>
      <div id="password_inputmiddle">
        <input type="password" name="user[password]" id="url" value="Password" onclick="this.value = ''">
        <img id="url_password" src="./images/passicon.png" alt="">
      </div>
      <div id="password_inputright"></div>
    </div>

    <div id="submit">
      <%= submit_tag 'sign up'%>
    </div>

  </div>

  <div id="wrapperbottom"></div>

  <div id="powered">
    <p>Powered by <a href="https://www.facebook.com/vijay.velu.3">Vijay</a></p>
  </div>
</div>

</body>
</html>